"""Sample plausible act-1 Ironclad combat positions for training a deck-conditioned model.

The combat value function is queried at ``(deck, relics, hp, encounter)``. Sampling those
factors independently wastes almost all of the capacity on positions the game cannot
produce -- a starter deck against the act boss, an eight-card deck at the first weak
combat -- so this samples the JOINT, conditioned on the encounter class.

The class-conditioned shapes below were measured off the run engine rather than guessed:
300 act-1 runs under random-but-legal choices, with max HP inflated at reset so routing
is not truncated by a random policy dying on floor 4 (``scripts/measure_positions.py``).

    class    floor p10-p50-p90   non-starter cards   non-starter relics
    weak             2-3-5               0-1-3               0-2
    normal          6-11-15              1-3-6               1-3
    elite           7-12-15              1-4-6               1-4
    boss            17-17-17             3-5-8               3-5

Two of those columns are measurement and one is prior. The card counts and floors are
measured. The RELIC counts are not: the random router reached the boss having fought a
median of two elites yet holding a median of two non-starter relics, when Neow plus the
guaranteed treasure room should already supply about that many before any elite drops
one. Something in the random policy leaves the relic-reward screen without claiming, so
the measured relic counts are a floor rather than a distribution, and the numbers above
are a competent-player prior instead. Re-derive them from run-level self-play once a run
policy exists.

Likewise the HP distribution is a pure guess: the measurement harness inflates max HP to
keep runs alive, so it cannot observe HP at all.
"""

from __future__ import annotations

import ctypes
import random
import re
from dataclasses import dataclass, field
from pathlib import Path

from . import native

_GENERATED = Path(__file__).resolve().parents[1] / "Sts2Emulator" / "Generated"
_RUN_CONSTANTS = (
    Path(__file__).resolve().parents[1] / "Sts2Emulator" / "Core" / "Run" / "RunConstants.cs"
)

# ── game data, parsed from the generated tables ───────────────────────────────
# Parsed rather than restated: these files are regenerated by scripts/extract_data.py on
# every patch, so a copy here would be wrong the first time a card changes rarity.


@dataclass(frozen=True)
class CardDef:
    card_id: int
    name: str
    entry: str
    type: str
    rarity: str


def _load_cards() -> dict[int, CardDef]:
    text = (_GENERATED / "Cards.g.cs").read_text()
    out: dict[int, CardDef] = {}
    for m in re.finditer(
        r'Id: (\d+), Name: "([^"]*)", Entry: "([^"]*)".*?'
        r"Type: CardType\.(\w+), Rarity: CardRarity\.(\w+)",
        text,
    ):
        card_id = int(m.group(1))
        out[card_id] = CardDef(card_id, m.group(2), m.group(3), m.group(4), m.group(5))
    return out


def _load_pool(name: str) -> list[int]:
    text = (_GENERATED / "CardPools.g.cs").read_text()
    m = re.search(rf"{name} =>\s*\[([^\]]*)\]", text)
    if m is None:
        raise RuntimeError(f"card pool {name} not found in CardPools.g.cs")
    return [int(x) for x in m.group(1).replace("\n", "").split(",") if x.strip()]


def _load_relics() -> dict[int, tuple[str, str]]:
    text = (_GENERATED / "Relics.g.cs").read_text()
    return {
        int(m.group(1)): (m.group(2), m.group(3))
        for m in re.finditer(
            r'Id: (\d+), Name: "([^"]*)", Entry: "[^"]*", Rarity: RelicRarity\.(\w+)', text,
        )
    }


def _load_encounters(name: str) -> list[int]:
    text = _RUN_CONSTANTS.read_text()
    m = re.search(rf"{name} =>\s*\[([^\]]*)\]", text)
    if m is None:
        raise RuntimeError(f"encounter pool {name} not found in RunConstants.cs")
    return [int(x) for x in m.group(1).replace("\n", "").split(",") if x.strip()]


CARDS = _load_cards()
IRONCLAD_POOL = _load_pool("Ironclad")
COLORLESS_POOL = _load_pool("Colorless")
CURSE_POOL = _load_pool("Curse")
RELICS = _load_relics()

STARTER_DECK = [472] * 5 + [131] * 4 + [30, 10001]
"""5 Strike, 4 Defend, Bash, Ascender's Bane -- `NativeExports.StarterDeckIds`."""

BURNING_BLOOD = 36
"""The Ironclad's starter relic. Always held, never sampled."""

ENCOUNTERS: dict[str, dict[str, list[int]]] = {
    "overgrowth": {
        "weak": _load_encounters("OvergrowthWeakEncounters"),
        "normal": _load_encounters("OvergrowthNormalEncounters"),
        "elite": _load_encounters("OvergrowthEliteEncounters"),
        "boss": _load_encounters("OvergrowthBossEncounters"),
    },
    "underdocks": {
        "weak": _load_encounters("UnderdocksWeakEncounters"),
        "normal": _load_encounters("UnderdocksNormalEncounters"),
        "elite": _load_encounters("UnderdocksEliteEncounters"),
        "boss": _load_encounters("UnderdocksBossEncounters"),
    },
}

CLASSES = ("weak", "normal", "elite", "boss")

# ── the measured shapes ───────────────────────────────────────────────────────
# (p10, p50, p90) per class, as measured above. Sampled as a triangular so the median is
# the mode and the tails reach the deciles; the point is a plausible spread, not a
# faithful reproduction of a distribution measured to two significant figures.

FLOOR_BY_CLASS = {
    "weak": (2, 3, 5),
    "normal": (6, 11, 15),
    "elite": (7, 12, 15),
    "boss": (17, 17, 17),
}
CARDS_BY_CLASS = {
    "weak": (0, 1, 3),
    "normal": (1, 3, 6),
    "elite": (1, 4, 6),
    "boss": (3, 5, 8),
}

RELICS_BY_CLASS = {
    "weak": (0, 1, 2),
    "normal": (1, 2, 3),
    "elite": (1, 2, 4),
    "boss": (3, 4, 5),
}
"""Prior, not measurement -- see the module docstring."""

RARITY_MIX = {"Common": 0.511, "Uncommon": 0.363, "Rare": 0.041, "Curse": 0.043}
"""Measured over 700 non-starter cards in act-1 boss decks.

Rare lands at 4.1% against the 1.49% base rate for a normal combat because the running
pity offset, the elite's 5% and the boss's guaranteed rare all feed the same deck. The
~4% tail of Event/Basic/Ancient/Quest cards the measurement also saw is dropped: those
come from specific events and shops that a class-conditioned sampler has no way to place.
"""

UPGRADE_FRACTION = 0.15
"""Prior. The measurement says 5.9%, but a random router almost never spends a rest on an
upgrade; a competent one upgrades considerably more."""

ENCHANT_FRACTION = 0.08
"""Prior. Act 1 grants enchantments through events and five Shop relics, of which the
emulator models neither the relics nor nine of the enchantments -- see
docs/enchantment-coverage.md. Until that lands this can only draw from the implemented
13, so the sampler under-represents the mechanic no matter what this is set to."""

IMPLEMENTED_ENCHANTMENTS = tuple(range(1, 14))
"""Enchantment enum values 1..13. Values are appended, never inserted, so a widened range
is all that is needed when the missing nine land."""

ASCENSION = 8
STARTING_MAX_HP = 80

RELIC_RARITY_WEIGHTS = {
    "Common": 0.34,
    "Uncommon": 0.26,
    "Rare": 0.13,
    "Shop": 0.13,
    "Event": 0.10,
    "Ancient": 0.04,
}
"""Roughly the mix act 1 can deal: commons dominate, Ancient only after the act boss."""

DECOUPLE_RELICS = 0.3
"""How often to break the card/relic coupling deliberately.

Cards and relics correlate in real runs (r=+0.66 cards~combats, +0.56 relics~elites), so
the honest joint keeps them coupled. But the whole job of the value function is answering
counterfactual deltas -- V(deck + card) - V(deck), V(relics + r) - V(relics) -- and under
a perfectly coupled training distribution both are extrapolation, with nothing to stop the
net attributing a relic's contribution to the deck that came with it. So most samples keep
the coupling and a minority resamples relics independently within the class range.
"""


# A triangular's own 10th and 90th percentiles sit well inside its support -- for a
# symmetric one they span about 55% of it -- so feeding measured deciles in as the
# endpoints produces a visibly narrower spread than was measured. Widen the support so the
# DECILES land where the measurement put them.
_DECILE_SPAN = 0.55


def _triangular_int(rng: random.Random, p10: int, p50: int, p90: int) -> int:
    """Draw an int whose 10th/50th/90th percentiles are approximately the arguments."""
    if p10 == p90:
        return p50
    lo = p50 - (p50 - p10) / _DECILE_SPAN
    hi = p50 + (p90 - p50) / _DECILE_SPAN
    return max(p10 - 1, min(p90 + 1, round(rng.triangular(lo, hi, p50))))


@dataclass
class Position:
    """A combat position, ready to be handed to ``native.reset_arena``."""

    deck: list[int]
    enchantments: list[tuple[int, int]]
    relics: list[int]
    potions: list[int]
    player_hp: int
    player_max_hp: int
    encounter_id: int
    floor: int
    klass: str
    act: str
    ascension: int = ASCENSION
    meta: dict = field(default_factory=dict)

    @property
    def completed_combat_rooms(self) -> int:
        """Weak variants are selected by a completed-combat count in [0,3)."""
        return 0 if self.klass == "weak" else -1

    def reset_into(self, handle: int, obs_buf: ctypes.Array) -> None:
        native.reset_arena(
            handle,
            self.deck,
            obs_buf,
            enchantments=self.enchantments,
            encounter_id=self.encounter_id,
            relic_ids=self.relics,
            potion_ids=self.potions,
            player_hp=self.player_hp,
            player_max_hp=self.player_max_hp,
            ascension=self.ascension,
            total_floor=self.floor,
            completed_combat_rooms=self.completed_combat_rooms,
        )


class PositionSampler:
    def __init__(self, character_pool: list[int] | None = None):
        self.pool = character_pool if character_pool is not None else IRONCLAD_POOL
        self._by_rarity: dict[str, list[int]] = {}
        for card_id in self.pool + COLORLESS_POOL:
            self._by_rarity.setdefault(CARDS[card_id].rarity, []).append(card_id)
        self._by_rarity["Curse"] = list(CURSE_POOL)
        self._relics_by_rarity: dict[str, list[int]] = {}
        for relic_id, (_, rarity) in RELICS.items():
            if relic_id != BURNING_BLOOD:
                self._relics_by_rarity.setdefault(rarity, []).append(relic_id)

    def sample(self, rng: random.Random, klass: str | None = None, act: str | None = None) -> Position:
        klass = klass or rng.choice(CLASSES)
        act = act or rng.choice(("overgrowth", "underdocks"))

        floor = max(1, _triangular_int(rng, *FLOOR_BY_CLASS[klass]))
        n_cards = max(0, _triangular_int(rng, *CARDS_BY_CLASS[klass]))

        # Relics stay coupled to the deck most of the time and are cut loose the rest --
        # see DECOUPLE_RELICS for why both are wanted.
        lo, _, hi = RELICS_BY_CLASS[klass]
        if rng.random() < DECOUPLE_RELICS:
            n_relics = rng.randint(lo, hi)
        else:
            span = CARDS_BY_CLASS[klass][2] - CARDS_BY_CLASS[klass][0] or 1
            frac = (n_cards - CARDS_BY_CLASS[klass][0]) / span
            n_relics = max(lo, min(hi, round(lo + frac * (hi - lo))))

        deck = [*STARTER_DECK, *(self._sample_card(rng) for _ in range(n_cards))]

        enchantments = self._sample_enchantments(rng, deck)
        relics = self._sample_relics(rng, n_relics)
        potions = self._sample_potions(rng)
        max_hp = STARTING_MAX_HP
        hp = self._sample_hp(rng, floor, max_hp, klass)

        return Position(
            deck=deck,
            enchantments=enchantments,
            relics=[BURNING_BLOOD, *relics],
            potions=potions,
            player_hp=hp,
            player_max_hp=max_hp,
            encounter_id=rng.choice(ENCOUNTERS[act][klass]),
            floor=floor,
            klass=klass,
            act=act,
            meta={"n_cards": n_cards, "n_relics": n_relics},
        )

    # ── the pieces ────────────────────────────────────────────────────────────

    def _sample_card(self, rng: random.Random) -> int:
        rarity = rng.choices(list(RARITY_MIX), weights=list(RARITY_MIX.values()))[0]
        card_id = rng.choice(self._by_rarity[rarity])
        # A curse is never upgraded; anything else may be.
        if rarity != "Curse" and rng.random() < UPGRADE_FRACTION:
            return -card_id
        return card_id

    @staticmethod
    def _sample_enchantments(
        rng: random.Random, deck: list[int],
    ) -> list[tuple[int, int]]:
        """One enchantment slot per deck index, 0 for none.

        Legality is asked of the engine (``native.can_enchant``) rather than restated:
        ``reset_arena`` applies whatever it is handed, so nothing downstream would catch
        a Nimble on an attack.
        """
        out: list[tuple[int, int]] = []
        for card_id in deck:
            if rng.random() >= ENCHANT_FRACTION:
                out.append((0, 0))
                continue
            legal = [e for e in IMPLEMENTED_ENCHANTMENTS if native.can_enchant(card_id, e)]
            if not legal:
                out.append((0, 0))
                continue
            enchantment = rng.choice(legal)
            # Self-Help Book grants Sharp/Nimble/Swift at 2; the event enchantments are
            # all applied at 1.
            out.append((enchantment, 2 if enchantment in (1, 2, 3) else 1))
        return out

    def _sample_relics(self, rng: random.Random, count: int) -> list[int]:
        """Draw `count` DISTINCT relics, weighted by the rarity mix act 1 can deal.

        Distinctness is the whole reason this is not a `rng.sample` over a list that
        repeats ids to encode their weight: that hands back the same relic twice, and a
        position holding two Vajras is one the game cannot produce.
        """
        chosen: list[int] = []
        pools = {r: list(ids) for r, ids in self._relics_by_rarity.items() if ids}
        rarities = [r for r in RELIC_RARITY_WEIGHTS if r in pools]
        while len(chosen) < count and rarities:
            weights = [RELIC_RARITY_WEIGHTS[r] for r in rarities]
            rarity = rng.choices(rarities, weights=weights)[0]
            chosen.append(pools[rarity].pop(rng.randrange(len(pools[rarity]))))
            if not pools[rarity]:
                rarities.remove(rarity)
        return chosen

    @staticmethod
    def _sample_potions(rng: random.Random) -> list[int]:  # noqa: ARG004
        # Three slots, and always empty for now: whether a position holds a potion is a
        # decision the run policy makes, and modelling it as a coin flip here would put
        # free resources into the value function's training data that no run earned.
        return []

    @staticmethod
    def _sample_hp(rng: random.Random, floor: int, max_hp: int, klass: str) -> int:  # noqa: ARG004
        """Prior, not measurement -- the harness inflates max HP and cannot observe this.

        HP drifts down over an act and a boss is usually met on less than a full bar.
        """
        # A run STARTS at 64/80 = 0.80 at this ascension, so that is the ceiling at floor
        # 1, not 1.0; HP only climbs above it through rests and heals.
        start = 64 / STARTING_MAX_HP
        centre = start - 0.025 * (floor - 1)
        frac = rng.triangular(max(0.15, centre - 0.32), min(1.0, centre + 0.22), centre)
        return max(1, min(max_hp, round(frac * max_hp)))
