// <auto-generated>
//     Generated by scripts/generate_event_gating_coverage.py. Do not edit by hand.
// </auto-generated>
namespace Sts2Emulator.Tests;

/// <summary>
/// Every event that overrides <c>IsAllowed</c> in the decompiled source.
///
/// <para>
/// <c>IsEventAllowed</c> ends in <c>_ =&gt; true</c>, so an event whose rule nobody
/// transcribed is silently allowed -- it turns up where the game would never
/// offer it, and shifts every later event in the sequence with it. That is how
/// War Historian Repy, whose rule is <c>return false</c>, was handed out as an
/// ordinary event.
/// </para>
/// <para>
/// This says only which events HAVE a rule, never what the rule is; the condition
/// is arbitrary code and still has to be read off the source by hand.
/// </para>
/// </summary>
public static class EventGatingCoverage
{
    public static readonly string[] EventsWithARule =
    [
        "Amalgamator",
        "BrainLeech",
        "ByrdonisNest",
        "ColorfulPhilosophers",
        "ColossalFlower",
        "CrystalSphere",
        "DenseVegetation",
        "DollRoom",
        "EndlessConveyor",
        "FakeMerchant",
        "FieldOfManSizedHoles",
        "GraveOfTheForgotten",
        "LuminousChoir",
        "MorphicGrove",
        "PotionCourier",
        "PunchOff",
        "RanwidTheElder",
        "RelicTrader",
        "RoomFullOfCheese",
        "RoundTeaParty",
        "SlipperyBridge",
        "SpiralingWhirlpool",
        "StoneOfAllTime",
        "Symbiote",
        "TeaMaster",
        "TheFutureOfPotions",
        "TheLegendsWereTrue",
        "TrashHeap",
        "UnrestSite",
        "WarHistorianRepy",
        "WaterloggedScriptorium",
        "WelcomeToWongos",
        "WhisperingHollow",
        "WoodCarvings",
        "ZenWeaver",
    ];
}
