// <auto-generated>
//     Generated by scripts/generate_event_captures.py. Do not edit by hand.
// </auto-generated>
using Sts2Emulator.Core;
using Sts2Emulator.Core.Run;
using Xunit;

namespace Sts2Emulator.Tests;

/// <summary>
/// Event outcomes compared against captures of the live game.
///
/// <para>
/// Every other event suite derives its expectations from the decompiled source.
/// That is ground truth for the rules, but a transcription error that is
/// self-consistent between the reading and the test survives it. These
/// assertions come from a real run of the real game and cannot.
/// </para>
/// <para>
/// Regenerate with <c>python scripts/generate_event_captures.py</c> after
/// re-capturing a fixture.
/// </para>
/// <item><description>DenseVegetation-opt1: page shape not asserted (mid-transition)</description></item>
/// </summary>
public class EventCaptures
{
    /// <summary>
    /// The state every capture was taken in: seed ABCDEF, A8, floor 1.
    ///
    /// <para>
    /// This enters through <c>BeginEvent</c> rather than assigning <c>EventId</c>,
    /// because entering an event runs its <c>CalculateVars</c> and several events draw
    /// from their own stream there. Assigning the id leaves those draws unspent and
    /// every later draw in the event lands one position early.
    /// </para>
    /// </summary>
    private static RunEngine Open(int eventId)
    {
        var engine = new RunEngine();
        engine.Reset("ABCDEF");
        RunNonCombatEffects.BeginEvent(engine.State, eventId);
        return engine;
    }

    private static int OfferedCount(RunEngine engine)
    {
        var mask = new int[RunConstants.MaxActions];
        engine.WriteActionMask(mask);
        return Enumerable
            .Range(0, RunConstants.EventSkipAction)
            .Count(index => mask[index] != 0);
    }

    private static void AssertPlayer(
        RunEngine engine,
        int hp,
        int maxHp,
        int gold,
        (int Card, bool Upgraded)[] deck,
        int[] relics
    )
    {
        Assert.Equal(hp, engine.State.PlayerHp);
        Assert.Equal(maxHp, engine.State.PlayerMaxHp);
        Assert.Equal(gold, engine.State.Gold);
        Assert.Equal(
            deck,
            engine.State.Deck.Select(card => (card.DefId, card.Upgraded)).ToArray()
        );
        Assert.Equal(relics, engine.State.Relics.Select(relic => relic.DefId).ToArray());
    }

    /// <summary>
    /// AbyssalBaths, 'Immerse' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void AbyssalBaths_Option0()
    {
        var engine = Open(RunConstants.EventAbyssalBaths);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 63, 82, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        // The game answered with a page of 2: 'Linger', 'Exit Baths'.
        Assert.Equal(2, OfferedCount(engine));
        Assert.NotEqual(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// AbyssalBaths, 'Abstain' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void AbyssalBaths_Option1()
    {
        var engine = Open(RunConstants.EventAbyssalBaths);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 74, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// Amalgamator, 'Combine Strikes' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void Amalgamator_Option0()
    {
        var engine = Open(RunConstants.EventAmalgamator);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// Amalgamator, 'Combine Defends' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void Amalgamator_Option1()
    {
        var engine = Open(RunConstants.EventAmalgamator);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// AromaOfChaos, 'Let Go' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void AromaOfChaos_Option0()
    {
        var engine = Open(RunConstants.EventAromaOfChaos);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// AromaOfChaos, 'Maintain Control' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void AromaOfChaos_Option1()
    {
        var engine = Open(RunConstants.EventAromaOfChaos);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// BrainLeech, 'Share Knowledge' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void BrainLeech_Option0()
    {
        var engine = Open(RunConstants.EventBrainLeech);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// BrainLeech, 'Rip the Leech Off' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void BrainLeech_Option1()
    {
        var engine = Open(RunConstants.EventBrainLeech);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 59, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.RelicReward, engine.State.Phase);
    }
    /// <summary>
    /// Bugslayer, 'Learn Extermination Technique' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void Bugslayer_Option0()
    {
        var engine = Open(RunConstants.EventBugslayer);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (178, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// Bugslayer, 'Learn Squash Technique' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void Bugslayer_Option1()
    {
        var engine = Open(RunConstants.EventBugslayer);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (459, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// ByrdonisNest, 'Eat the Egg' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void ByrdonisNest_Option0()
    {
        var engine = Open(RunConstants.EventByrdonisNest);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 71, 87, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// ByrdonisNest, 'Take the Egg' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void ByrdonisNest_Option1()
    {
        var engine = Open(RunConstants.EventByrdonisNest);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (10022, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// CrystalSphere, 'Uncover Future' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void CrystalSphere_Option0()
    {
        var engine = Open(RunConstants.EventCrystalSphere);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 20,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.CrystalSphere, engine.State.Phase);
    }
    /// <summary>
    /// CrystalSphere, 'Payment Plan' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void CrystalSphere_Option1()
    {
        var engine = Open(RunConstants.EventCrystalSphere);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (10025, false)],
            [36]);
        Assert.Equal(RunPhase.CrystalSphere, engine.State.Phase);
    }
    /// <summary>
    /// DenseVegetation, 'Trudge On' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void DenseVegetation_Option0()
    {
        var engine = Open(RunConstants.EventDenseVegetation);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 56, 80, 175,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// DenseVegetation, 'Rest' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void DenseVegetation_Option1()
    {
        var engine = Open(RunConstants.EventDenseVegetation);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 80, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        // Page shape not asserted: this capture landed mid-transition.
    }
    /// <summary>
    /// DollRoom, 'Pick at Random' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void DollRoom_Option0()
    {
        var engine = Open(RunConstants.EventDollRoom);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 57]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// DollRoom, 'Take Some Time' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void DollRoom_Option1()
    {
        var engine = Open(RunConstants.EventDollRoom);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 59, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        // The game answered with a page of 2: 'Daughter of the Wind', 'Mr. Struggles'.
        Assert.Equal(2, OfferedCount(engine));
        Assert.NotEqual(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// DollRoom, 'Examine Each and Make the Best Choice' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void DollRoom_Option2()
    {
        var engine = Open(RunConstants.EventDollRoom);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(2, -1, out _, out _, out _));

        AssertPlayer(engine, 49, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        // The game answered with a page of 3: 'Daughter of the Wind', 'Mr. Struggles', 'Bing Bong'.
        Assert.Equal(3, OfferedCount(engine));
        Assert.NotEqual(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// DoorsOfLightAndDark, 'Light Door' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void DoorsOfLightAndDark_Option0()
    {
        var engine = Open(RunConstants.EventDoorsOfLightAndDark);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, true), (472, false), (131, false), (131, false), (131, true), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// DoorsOfLightAndDark, 'Dark Door' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void DoorsOfLightAndDark_Option1()
    {
        var engine = Open(RunConstants.EventDoorsOfLightAndDark);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// DrowningBeacon, 'Bottle' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void DrowningBeacon_Option0()
    {
        var engine = Open(RunConstants.EventDrowningBeacon);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.RelicReward, engine.State.Phase);
    }
    /// <summary>
    /// DrowningBeacon, 'Climb' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void DrowningBeacon_Option1()
    {
        var engine = Open(RunConstants.EventDrowningBeacon);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 67, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 92]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// EndlessConveyor, 'Grab Fried Eel off the Belt' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void EndlessConveyor_Option0()
    {
        var engine = Open(RunConstants.EventEndlessConveyor);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 59,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (80, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        // The game answered with a page of 2: 'Grab Jelly Liver off the Belt', 'Leave'.
        Assert.Equal(2, OfferedCount(engine));
        Assert.NotEqual(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// EndlessConveyor, 'Observe the Chef' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void EndlessConveyor_Option1()
    {
        var engine = Open(RunConstants.EventEndlessConveyor);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, true), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// HungryForMushrooms, 'Big Mushroom' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void HungryForMushrooms_Option0()
    {
        var engine = Open(RunConstants.EventHungryForMushrooms);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 84, 100, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 16]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// HungryForMushrooms, 'Fragrant Mushroom' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void HungryForMushrooms_Option1()
    {
        var engine = Open(RunConstants.EventHungryForMushrooms);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 49, 80, 99,
            [(472, false), (472, false), (472, false), (472, true), (472, false), (131, false), (131, false), (131, true), (131, false), (30, false), (10001, false)],
            [36, 91]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// InfestedAutomaton, 'Study' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void InfestedAutomaton_Option0()
    {
        var engine = Open(RunConstants.EventInfestedAutomaton);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (185, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// InfestedAutomaton, 'Touch the Core' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void InfestedAutomaton_Option1()
    {
        var engine = Open(RunConstants.EventInfestedAutomaton);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (13, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// JungleMazeAdventure, 'Solo Quest' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void JungleMazeAdventure_Option0()
    {
        var engine = Open(RunConstants.EventJungleMazeAdventure);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 46, 80, 257,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// JungleMazeAdventure, 'Join Forces' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void JungleMazeAdventure_Option1()
    {
        var engine = Open(RunConstants.EventJungleMazeAdventure);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 150,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// LostWisp, 'Capture the Wisp' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void LostWisp_Option0()
    {
        var engine = Open(RunConstants.EventLostWisp);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (10026, false)],
            [36, 141]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// LostWisp, 'Search the Nearby Area' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void LostWisp_Option1()
    {
        var engine = Open(RunConstants.EventLostWisp);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 169,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// LuminousChoir, 'Reach into the Flesh' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void LuminousChoir_Option0()
    {
        var engine = Open(RunConstants.EventLuminousChoir);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// MorphicGrove, 'Group' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void MorphicGrove_Option0()
    {
        var engine = Open(RunConstants.EventMorphicGrove);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 0,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// MorphicGrove, 'Loner' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void MorphicGrove_Option1()
    {
        var engine = Open(RunConstants.EventMorphicGrove);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 69, 85, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// PotionCourier, 'Grab Potions' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void PotionCourier_Option0()
    {
        var engine = Open(RunConstants.EventPotionCourier);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.RelicReward, engine.State.Phase);
    }
    /// <summary>
    /// PotionCourier, 'Ransack' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void PotionCourier_Option1()
    {
        var engine = Open(RunConstants.EventPotionCourier);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.RelicReward, engine.State.Phase);
    }
    /// <summary>
    /// PunchOff, 'Nab' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void PunchOff_Option0()
    {
        var engine = Open(RunConstants.EventPunchOff);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (10031, false)],
            [36]);
        Assert.Equal(RunPhase.RelicReward, engine.State.Phase);
    }
    /// <summary>
    /// PunchOff, 'I Can Take Them' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void PunchOff_Option1()
    {
        var engine = Open(RunConstants.EventPunchOff);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        // The game answered with a page of 1: 'Fight'.
        Assert.Equal(1, OfferedCount(engine));
        Assert.NotEqual(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// RanwidTheElder, 'Give 100 Gold' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void RanwidTheElder_Option1()
    {
        var engine = Open(RunConstants.EventRanwidTheElder);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 0,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 172]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// RelicTrader, 'Proceed' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void RelicTrader_Option0()
    {
        var engine = Open(RunConstants.EventRelicTrader);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// RoomFullOfCheese, 'Gorge' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void RoomFullOfCheese_Option0()
    {
        var engine = Open(RunConstants.EventRoomFullOfCheese);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// RoomFullOfCheese, 'Search' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void RoomFullOfCheese_Option1()
    {
        var engine = Open(RunConstants.EventRoomFullOfCheese);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 50, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 48]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// SapphireSeed, 'Consume' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SapphireSeed_Option0()
    {
        var engine = Open(RunConstants.EventSapphireSeed);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 73, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// SapphireSeed, 'Plant and Nourish' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SapphireSeed_Option1()
    {
        var engine = Open(RunConstants.EventSapphireSeed);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// SelfHelpBook, 'Read the Back' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SelfHelpBook_Option0()
    {
        var engine = Open(RunConstants.EventSelfHelpBook);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// SelfHelpBook, 'Read a Random Passage' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SelfHelpBook_Option1()
    {
        var engine = Open(RunConstants.EventSelfHelpBook);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// SlipperyBridge, 'Overcome' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SlipperyBridge_Option0()
    {
        var engine = Open(RunConstants.EventSlipperyBridge);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// SlipperyBridge, 'Hold On' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SlipperyBridge_Option1()
    {
        var engine = Open(RunConstants.EventSlipperyBridge);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 61, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        // The game answered with a page of 2: 'Overcome', 'Hold On'.
        Assert.Equal(2, OfferedCount(engine));
        Assert.NotEqual(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// SpiralingWhirlpool, 'Observe' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SpiralingWhirlpool_Option0()
    {
        var engine = Open(RunConstants.EventSpiralingWhirlpool);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// SpiralingWhirlpool, 'Drink' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SpiralingWhirlpool_Option1()
    {
        var engine = Open(RunConstants.EventSpiralingWhirlpool);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 80, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// StoneOfAllTime, 'Push' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void StoneOfAllTime_Option1()
    {
        var engine = Open(RunConstants.EventStoneOfAllTime);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 58, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// SunkenStatue, 'Grab the Sword' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SunkenStatue_Option0()
    {
        var engine = Open(RunConstants.EventSunkenStatue);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 256]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// SunkenStatue, 'Dive into the Water' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SunkenStatue_Option1()
    {
        var engine = Open(RunConstants.EventSunkenStatue);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 57, 80, 208,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// SunkenTreasury, 'First Chest' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SunkenTreasury_Option0()
    {
        var engine = Open(RunConstants.EventSunkenTreasury);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 162,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// SunkenTreasury, 'Second Chest' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void SunkenTreasury_Option1()
    {
        var engine = Open(RunConstants.EventSunkenTreasury);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 439,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (10029, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// Symbiote, 'Approach' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void Symbiote_Option0()
    {
        var engine = Open(RunConstants.EventSymbiote);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// Symbiote, 'Kill with Fire' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void Symbiote_Option1()
    {
        var engine = Open(RunConstants.EventSymbiote);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// TabletOfTruth, 'Decipher' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void TabletOfTruth_Option0()
    {
        var engine = Open(RunConstants.EventTabletOfTruth);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 77, 99,
            [(472, false), (472, true), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        // The game answered with a page of 2: 'Continue Deciphering', 'Give Up'.
        Assert.Equal(2, OfferedCount(engine));
        Assert.NotEqual(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// TabletOfTruth, 'Smash' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void TabletOfTruth_Option1()
    {
        var engine = Open(RunConstants.EventTabletOfTruth);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 80, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// TeaMaster, 'Bone Tea' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void TeaMaster_Option0()
    {
        var engine = Open(RunConstants.EventTeaMaster);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 49,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 25]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// TeaMaster, 'Tea of Discourtesy' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void TeaMaster_Option2()
    {
        var engine = Open(RunConstants.EventTeaMaster);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(2, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 259]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// TheLanternKey, 'Return the Key' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void TheLanternKey_Option0()
    {
        var engine = Open(RunConstants.EventTheLanternKey);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 199,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// TheLanternKey, 'Keep the Key' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void TheLanternKey_Option1()
    {
        var engine = Open(RunConstants.EventTheLanternKey);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        // The game answered with a page of 1: 'Fight'.
        Assert.Equal(1, OfferedCount(engine));
        Assert.NotEqual(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// TheLegendsWereTrue, 'Nab the Map' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void TheLegendsWereTrue_Option0()
    {
        var engine = Open(RunConstants.EventTheLegendsWereTrue);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (10020, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// TheLegendsWereTrue, 'Slowly Find an Exit' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void TheLegendsWereTrue_Option1()
    {
        var engine = Open(RunConstants.EventTheLegendsWereTrue);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 56, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.RelicReward, engine.State.Phase);
    }
    /// <summary>
    /// ThisOrThat, 'This' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void ThisOrThat_Option0()
    {
        var engine = Open(RunConstants.EventThisOrThat);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 58, 80, 161,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// ThisOrThat, 'That' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void ThisOrThat_Option1()
    {
        var engine = Open(RunConstants.EventThisOrThat);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (10023, false)],
            [36, 172]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// TrashHeap, 'Dive In' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void TrashHeap_Option0()
    {
        var engine = Open(RunConstants.EventTrashHeap);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 56, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 109]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// TrashHeap, 'Grab Random Junk' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void TrashHeap_Option1()
    {
        var engine = Open(RunConstants.EventTrashHeap);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 199,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (167, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// UnrestSite, 'Rest Anyways' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void UnrestSite_Option0()
    {
        var engine = Open(RunConstants.EventUnrestSite);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 80, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false), (10035, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// UnrestSite, 'Kill the Trees' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void UnrestSite_Option1()
    {
        var engine = Open(RunConstants.EventUnrestSite);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 72, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 172]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// WarHistorianRepy, 'Unlock the Cage' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WarHistorianRepy_Option0()
    {
        var engine = Open(RunConstants.EventWarHistorianRepy);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36, 113]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// WarHistorianRepy, 'Unlock the Chest' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WarHistorianRepy_Option1()
    {
        var engine = Open(RunConstants.EventWarHistorianRepy);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.RelicReward, engine.State.Phase);
    }
    /// <summary>
    /// WaterloggedScriptorium, 'Bloody Ink' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WaterloggedScriptorium_Option0()
    {
        var engine = Open(RunConstants.EventWaterloggedScriptorium);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 70, 86, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// WaterloggedScriptorium, 'Tentacle Quill' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WaterloggedScriptorium_Option1()
    {
        var engine = Open(RunConstants.EventWaterloggedScriptorium);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 44,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// WaterloggedScriptorium, 'Prickly Sponge' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WaterloggedScriptorium_Option2()
    {
        var engine = Open(RunConstants.EventWaterloggedScriptorium);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(2, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 0,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// WelcomeToWongos, 'Leave' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WelcomeToWongos_Option3()
    {
        var engine = Open(RunConstants.EventWelcomeToWongos);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(3, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.Event, engine.State.Phase);
        Assert.Equal(RunConstants.EventResultPending, engine.State.EventId);
    }
    /// <summary>
    /// Wellspring, 'Bottle' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void Wellspring_Option0()
    {
        var engine = Open(RunConstants.EventWellspring);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.RelicReward, engine.State.Phase);
    }
    /// <summary>
    /// Wellspring, 'Bathe' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void Wellspring_Option1()
    {
        var engine = Open(RunConstants.EventWellspring);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// WhisperingHollow, 'Exchange Gold' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WhisperingHollow_Option0()
    {
        var engine = Open(RunConstants.EventWhisperingHollow);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 56,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.RelicReward, engine.State.Phase);
    }
    /// <summary>
    /// WhisperingHollow, 'Hug the Tree' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WhisperingHollow_Option1()
    {
        var engine = Open(RunConstants.EventWhisperingHollow);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// WoodCarvings, 'Bird' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WoodCarvings_Option0()
    {
        var engine = Open(RunConstants.EventWoodCarvings);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(0, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// WoodCarvings, 'Snake' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WoodCarvings_Option1()
    {
        var engine = Open(RunConstants.EventWoodCarvings);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(1, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
    /// <summary>
    /// WoodCarvings, 'Torus' -- captured from v0.107.1 (build 23811903).
    /// </summary>
    [Fact]
    public void WoodCarvings_Option2()
    {
        var engine = Open(RunConstants.EventWoodCarvings);

        // The capture's own starting state. If this drifts, the after-state
        // comparison below is measuring two different runs.
        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);

        Assert.Equal(0, engine.Step(2, -1, out _, out _, out _));

        AssertPlayer(engine, 64, 80, 99,
            [(472, false), (472, false), (472, false), (472, false), (472, false), (131, false), (131, false), (131, false), (131, false), (30, false), (10001, false)],
            [36]);
        Assert.Equal(RunPhase.TransformSelect, engine.State.Phase);
    }
}
