using System.Reflection;
using Xunit;

namespace Sts2Emulator.Tests;

/// <summary>
/// Holds the line between "the emulator plays this card" and "we know it plays it
/// right". A card counts as covered when a <c>&lt;CardName&gt;Tests</c> class exists;
/// everything still uncovered is listed in <see cref="Pending"/>, so implementing a
/// card without either testing it or deliberately deferring it breaks the build.
///
/// <see cref="Pending"/> is a burn-down list, not a config knob: delete the name when
/// the tests land. Growing it is a decision worth arguing about in review.
/// </summary>
public class CardCoverageTests
{
    /// <summary>
    /// Cards implemented in <c>CardEffects.Apply</c> that no test exercises yet.
    /// Every entry is a card the emulator will happily play wrongly in silence.
    /// </summary>
    private static readonly HashSet<string> Pending =
    [
        "AdaptiveStrike",
        "Afterlife",
        "Alignment",
        "AllForOne",
        "Apotheosis",
        "Apparition",
        "Arsenal",
        "AstralPulse",
        "BansheesCry",
        "BeatIntoShape",
        "Beckon",
        "Begone",
        "BiasedCognition",
        "BigBang",
        "BlackHole",
        "BlightStrike",
        "Bodyguard",
        "Bombardment",
        "BoneShards",
        "BorrowedTime",
        "BrightestFlame",
        "Buffer",
        "Bulwark",
        "BundleOfJoy",
        "Burn",
        "Bury",
        "ByrdSwoop",
        "Calcify",
        "CallOfTheVoid",
        "Caltrops",
        "CaptureSpirit",
        "Cascade",
        "CelestialMight",
        "Charge",
        "ChildOfTheStars",
        "Clash",
        "Cleanse",
        "CloakOfStars",
        "CollisionCourse",
        "Comet",
        "Conqueror",
        "ConsumingShadow",
        "Convergence",
        "Coolant",
        "CosmicIndifference",
        "Countdown",
        "CrashLanding",
        "CreativeAi",
        "CrescentSpear",
        "CrushUnder",
        "DanseMacabre",
        "DeathMarch",
        "Deathbringer",
        "DeathsDoor",
        "Debilitate",
        "Debris",
        "DecisionsDecisions",
        "DefendNecrobinder",
        "DefendRegent",
        "Defile",
        "Defragment",
        "Defy",
        "Delay",
        "Demesne",
        "Devastate",
        "DevourLife",
        "Dirge",
        "Disintegration",
        "Distraction",
        "DrainPower",
        "Dredge",
        "DualWield",
        "DyingStar",
        "EchoForm",
        "Eidolon",
        "EndOfDays",
        "EnfeeblingTouch",
        "Enlightenment",
        "Enthralled",
        "Entrench",
        "Eradicate",
        "Exterminate",
        "FallingStar",
        "Fear",
        "FeedingFrenzy",
        "Fetch",
        "FlakCannon",
        "Flatten",
        "ForbiddenGrimoire",
        "ForegoneConclusion",
        "FranticEscape",
        "Friendship",
        "Fuel",
        "Furnace",
        "GammaBlast",
        "GatherLight",
        "Genesis",
        "GeneticAlgorithm",
        "Glimmer",
        "GlimpseBeyond",
        "Glitterstream",
        "Glow",
        "GraveWarden",
        "Graveblast",
        "Guards",
        "GuidingStar",
        "HammerTime",
        "Hang",
        "Haunt",
        "HeavenlyDrill",
        "Hegemony",
        "HeirloomHammer",
        "HelixDrill",
        "HelloWorld",
        "HiddenCache",
        "HighFive",
        "Hyperbeam",
        "IAmInvincible",
        "IceLance",
        "Ignition",
        "Infection",
        "Invoke",
        "KinglyKick",
        "KinglyPunch",
        "KnockoutBlow",
        "KnowThyPlace",
        "Largesse",
        "LegionOfBone",
        "Lethality",
        "Luminesce",
        "LunarBlast",
        "MachineLearning",
        "MadScience",
        "MakeItSo",
        "ManifestAuthority",
        "Maul",
        "Melancholy",
        "Metamorphosis",
        "MeteorShower",
        "MeteorStrike",
        "MinionDiveBomb",
        "MinionSacrifice",
        "MinionStrike",
        "Misery",
        "MonarchsGaze",
        "Monologue",
        "MultiCast",
        "NecroMastery",
        "NegativePulse",
        "Neurosurge",
        "NeutronAegis",
        "NoEscape",
        "Oblivion",
        "Orbit",
        "Outmaneuver",
        "Pagestorm",
        "PaleBlueDot",
        "Parry",
        "Parse",
        "ParticleWall",
        "Patter",
        "Peck",
        "PhotonCut",
        "PillarOfCreation",
        "Poke",
        "Prophesize",
        "Protector",
        "PullAggro",
        "PullFromBelow",
        "Putrefy",
        "Quadcast",
        "Quasar",
        "Radiate",
        "Rainbow",
        "Rattle",
        "Reanimate",
        "Reap",
        "ReaperForm",
        "Reave",
        "Reboot",
        "Rebound",
        "RefineBlade",
        "Reflect",
        "Relax",
        "Resonance",
        "RightHandHand",
        "RipAndTear",
        "RoyalGamble",
        "Royalties",
        "Sacrifice",
        "Scourge",
        "SculptingStrike",
        "Seance",
        "SeekingEdge",
        "SentryMode",
        "SevenStars",
        "Severance",
        "SharedFate",
        "Shatter",
        "ShiningStrike",
        "Shroud",
        "SicEm",
        "SignalBoost",
        "SleightOfFlesh",
        "Snap",
        "SolarStrike",
        "Soul",
        "SoulStorm",
        "SovereignBlade",
        "Sow",
        "SpectrumShift",
        "Spinner",
        "SpiritOfAsh",
        "SpoilsMap",
        "SpoilsOfBattle",
        "SporeMind",
        "Spur",
        "Squash",
        "Squeeze",
        "Stack",
        "Stardust",
        "StrikeNecrobinder",
        "StrikeRegent",
        "SummonForth",
        "Supercritical",
        "Supermassive",
        "SweepingGaze",
        "SwordSage",
        "Terraforming",
        "TheScythe",
        "TheSealedThrone",
        "TheSmith",
        "TimesUp",
        "ToricToughness",
        "Toxic",
        "Transfigure",
        "TrashToTreasure",
        "Tyranny",
        "Undeath",
        "Unleash",
        "Veilpiercer",
        "Venerate",
        "VoidForm",
        "Voltaic",
        "Whistle",
        "Wish",
        "Wisp",
        "Wither",
        "Wound",
        "WroughtInWar",
    ];

    [Fact]
    public void EveryImplementedCardHasATestSuite()
    {
        var missing = ImplementedCards
            .Names.Where(name => !HasSuite(name) && !Pending.Contains(name))
            .ToList();

        Assert.True(
            missing.Count == 0,
            $"Implemented with no <Name>Tests class: {string.Join(", ", missing)}. "
                + "Add the tests, or add the card to CardCoverageTests.Pending to defer it."
        );
    }

    [Fact]
    public void PendingListHasNoCardThatIsNowTested()
    {
        var stale = Pending.Where(HasSuite).OrderBy(name => name).ToList();

        Assert.True(
            stale.Count == 0,
            $"Now tested, so remove from CardCoverageTests.Pending: {string.Join(", ", stale)}."
        );
    }

    [Fact]
    public void PendingListHasNoCardThatIsNotImplemented()
    {
        var unknown = Pending.Except(ImplementedCards.Names).OrderBy(name => name).ToList();

        Assert.True(
            unknown.Count == 0,
            $"In CardCoverageTests.Pending but not implemented (renamed or dropped?): "
                + $"{string.Join(", ", unknown)}."
        );
    }

    private static bool HasSuite(string cardName) =>
        Assembly.GetExecutingAssembly().GetType($"Sts2Emulator.Tests.{cardName}Tests") != null;
}
