#!/usr/bin/env python3
"""Generate the list of events whose IsAllowed the emulator must transcribe.

An event that overrides ``IsAllowed`` refuses to appear under some condition.
``RunNonCombatEffects.IsEventAllowed`` ends in ``_ => true``, so an event nobody
transcribed is silently ALLOWED -- it does not fail, it just turns up where the
game would never offer it, and every later event in the sequence shifts with it.

That is exactly how War Historian Repy got handed out as an ordinary event. Its
rule is ``return false``: it is never drawn from the sequence at all. Nothing
caught it because the gate simply had no case for it.

This is not ground truth about the *rules* -- only about which events HAVE one.
The condition itself still has to be read off the decompiled source and written
by hand, because it is arbitrary code. What the guard removes is the silent
omission.

    python scripts/generate_event_gating_coverage.py
    python scripts/generate_event_gating_coverage.py --check
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EVENTS = REPO / "decompiled" / "MegaCrit.Sts2.Core.Models.Events"
GATE = REPO / "src" / "Sts2Emulator" / "Core" / "Run" / "RunNonCombatEffects.cs"
OUT = REPO / "src" / "Sts2Emulator.Tests" / "Events" / "EventGatingCoverage.g.cs"


def events_with_a_rule() -> list[str]:
    """Event class names that override IsAllowed.

    Raises:
        SystemExit: if the decompiled source is missing or has changed shape.

    """
    if not EVENTS.is_dir():
        raise SystemExit(
            f"{EVENTS} is missing. The decompiled source is not redistributed -- "
            "regenerate it with scripts/decompile.sh.",
        )
    found = [
        path.stem
        for path in sorted(EVENTS.glob("*.cs"))
        if r"public override bool IsAllowed" in path.read_text(errors="replace")
    ]
    if not found:
        raise SystemExit(
            "No IsAllowed overrides found — did the decompile shape change?",
        )
    return found


def render(names: list[str]) -> str:
    listed = "\n".join(f'        "{name}",' for name in names)
    return f"""// <auto-generated>
//     Generated by scripts/generate_event_gating_coverage.py. Do not edit by hand.
// </auto-generated>
namespace Sts2Emulator.Tests;

/// <summary>
/// Every event that overrides <c>IsAllowed</c> in the decompiled source.
///
/// <para>
/// <c>IsEventAllowed</c> ends in <c>_ =&gt; true</c>, so an event whose rule nobody
/// transcribed is silently allowed -- it turns up where the game would never
/// offer it, and shifts every later event in the sequence with it. That is how
/// War Historian Repy, whose rule is <c>return false</c>, was handed out as an
/// ordinary event.
/// </para>
/// <para>
/// This says only which events HAVE a rule, never what the rule is; the condition
/// is arbitrary code and still has to be read off the source by hand.
/// </para>
/// </summary>
public static class EventGatingCoverage
{{
    public static readonly string[] EventsWithARule =
    [
{listed}
    ];
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    names = events_with_a_rule()
    gate = GATE.read_text(encoding="utf-8")
    # The act-gated events are refused by a list just above the switch, so the
    # region that counts as "transcribed" starts there.
    start = gate.find("ActTwoAndLaterEvents =")
    if start < 0:
        start = gate.find("internal static bool IsEventAllowed")
    if start < 0:
        raise SystemExit("IsEventAllowed not found — did it get renamed?")
    end = gate.find("internal static bool IsEventAllowed", start)
    body = gate[start : gate.find("\n    }", end if end > 0 else start)]
    missing = [n for n in names if f"Event{n}" not in body]

    if args.check:
        print(
            f"{len(names)} events carry an IsAllowed rule; {len(missing)} untranscribed",
        )
        for name in missing:
            print(f"  missing: {name}")
        return

    OUT.write_text(render(names), encoding="utf-8")
    print(f"{len(names)} events with a rule -> {OUT.relative_to(REPO)}")
    if missing:
        print(f"  {len(missing)} not yet in IsEventAllowed: {', '.join(missing)}")


if __name__ == "__main__":
    main()
